version: '2'

services:
  server:
    image: celaraze/chemex:latest
    container_name: chemex-web
    depends_on:
     - mysql
    environment:
      TZ: Asia/Shanghai
      DB_HOST: "mysql"
      DB_DATABASE: "chemex"
      DB_USERNAME: "chemex"
      DB_PASSWORD: "chemex_pwd"
      INSTALL: "true"
    ports:
     - "8889:80"
    volumes:
     - /etc/localtime:/etc/localtime:ro
    links:
     - mysql:chemex-mysql
    user: root
    networks:
      chemex:
        ipv4_address: 172.26.0.4
    restart: always
  mysql:
    image: mysql:latest
    container_name: chemex-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: "chemex"
      MYSQL_USER: "chemex"
      MYSQL_PASSWORD: "chemex_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"     
    networks:
      chemex:
        ipv4_address: 172.26.0.3
    volumes:
     - /home/data/chemex/database/mysql:/var/lib/mysql
     - /etc/localtime:/etc/localtime:ro
    restart: always
networks:
  chemex:
    driver: bridge
    ipam:
     config:
       - subnet: 172.26.0.0/16
         gateway: 172.26.0.1
